spring.application.name=college_erp_management_system
spring.datasource.url=jdbc:mysql://localhost:3306/college_erp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.security=DEBUG

# spring.web.cors.allowed-origins=http://localhost:3000
# spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
# spring.web.cors.allowed-headers=*
# spring.web.cors.allow-credentials=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rohansamuel0806@gmail.com
spring.mail.password=ydso ylsh fxds yeao
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG

# cnho mtfr iyux pvgp

# zzuber144@gmail.com
# cbyf iiec jypc fzwn

# rohansamuel0806@gmail.com
# ydso ylsh fxds yeao